title: "Abdullah Ahmad Mirza"
description: "BS Computer Engineering | UET Lahore (Faisalabad Campus)"
theme: jekyll-theme-cayman
baseurl: "/my-website-1"
url: "https://abdullahahmad88.github.io"

# This helps GitHub find your posts correctly
permalink: /:year/:month/:day/:title/
